# Generated by Django 5.1.4 on 2025-01-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('Sáng', 'Sáng'), ('Chiều', 'Chiều'), ('Tối', 'Tối')], max_length=50)),
                ('activity', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.tour')),
            ],
            options={
                'verbose_name': 'Lịch trình',
                'verbose_name_plural': 'Lịch trình',
                'ordering': ['tour', 'day', 'period'],
            },
        ),
    ]
