# Generated by Django 5.1.4 on 2025-01-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name_tour', models.CharField(max_length=100, verbose_name='Tên tour')),
                ('description', models.TextField(max_length=200, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gía chuyến đi')),
                ('time', models.TimeField()),
                ('start_date', models.DateField(verbose_name='Ngày khởi hành')),
            ],
        ),
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.TextField(verbose_name='Lịch trình')),
                ('hotel', models.CharField(blank=True, max_length=255, verbose_name='Khách sạn')),
                ('meals', models.CharField(blank=True, max_length=255, verbose_name='Bữa ăn')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
    ]
