# Generated by Django 5.1.4 on 2025-01-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
