# Generated by Django 5.1.4 on 2025-01-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_booking_confirmation_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_of_travel',
        ),
    ]
